apiVersion: v1
kind: Service
metadata:
  labels:
    service: discovery
  name: discovery
spec:
  ports:
  - name: "8761"
    port: 8761
    targetPort: 8761
  selector:
    service: discovery
status:
  loadBalancer: {}
