apiVersion: v1
kind: Service
metadata:
  labels:
    service: dispatcher
  name: dispatcher
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 8100
  selector:
    service: dispatcher
status:
  loadBalancer: {}
