apiVersion: v1
kind: Service
metadata:
  labels:
    service: actuator
  name: actuator
spec:
  ports:
  - name: "8200"
    port: 8200
    targetPort: 8200
  selector:
    service: actuator
status:
  loadBalancer: {}
