apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      service: gateway
  strategy: {}
  template:
    metadata:
      labels:
        service: gateway
    spec:
      containers:
      - env:
        - name: EUREKA_SERVICE
          value: http://discovery:8761/eureka
        image: rfashwal/gateway:latest
        imagePullPolicy: ""
        name: gateway
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
