apiVersion: v1
kind: Service
metadata:
  labels:
    service: gateway
  name: gateway
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    service: gateway
status:
  loadBalancer: {}
