apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: rabbit
  name: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rabbit
  strategy: {}
  template:
    metadata:
      labels:
        service: rabbit
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
          value: guest1
        - name: RABBITMQ_DEFAULT_USER
          value: guest1
        image: rabbitmq:3-management
        imagePullPolicy: ""
        name: rabbit
        ports:
        - containerPort: 15672
        - containerPort: 5672
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
